export { ReactComponent as Arrow } from './arrow.svg'
export { ReactComponent as Calendar} from './calendar.svg'
export { ReactComponent as Check } from './check.svg'
export { ReactComponent as CheckCircle } from './check-circle.svg'
export { ReactComponent as CheckSquare} from './check-square.svg'
export { ReactComponent as Copy} from './copy.svg'
export { ReactComponent as DoubleArrow} from './double-arrow.svg'
export { ReactComponent as Edit } from './edit.svg'
export { ReactComponent as Eye } from './eye.svg'
export { ReactComponent as EyeSlash } from './eye-slash.svg'
export { ReactComponent as Arrows} from './move.svg'
export { ReactComponent as Paste} from './paste.svg'
export { ReactComponent as Plus } from './plus.svg'
export { ReactComponent as Search} from './search.svg'
export { ReactComponent as Spinner} from './spinner.svg'
export { ReactComponent as Times} from './times.svg'
export { ReactComponent as Trash } from './trash.svg'
export { ReactComponent as UploadSVG } from './upload.svg'
export { ReactComponent as User } from './user-circle.svg'
export { ReactComponent as Envelope } from './envelope.svg'
export { ReactComponent as Facebook } from './facebook.svg'
export { ReactComponent as Linkedin } from './linkedin.svg'
export { ReactComponent as MapMarked } from './map-marked.svg'
export { ReactComponent as Phone } from './phone.svg'
